version: '3.1'

services:

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - registrator
    links:
      - agent2:consul
    labels:
        "SERVICE_NAME": "APP"
        "SERVICE_TAGS": "app1"
        "SERVICE_CHECK_HTTP": "/health"
        "SERVICE_CHECK_INTERVAL": "5s"

  registrator:
    depends_on:
      - agent1
    image: gliderlabs/registrator:latest
    links:
      - agent1:consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    entrypoint: /bin/registrator consul://consul:8500

  seed:
    hostname: seed
    image: consul:0.8.0
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
    entrypoint:
      - timeout     
      - -sTERM      
      - -t300      
      - consul
      - agent
      - -server
      - -bootstrap-expect=2
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}

  agent1:
    image: consul:0.8.0
    depends_on:
      - "seed"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"dleave_on_terminate\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_HTTP_ADDR=0.0.0.0"
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -retry-join=seed:8301
      - -ui    
      - -node-id=d3c15603-463a-2197-016d-a37959e10100
    ports:
      - "8500:8500"
      - "8600:8600"
    labels:
      "SERVICE_IGNORE": "true"

  agent2:
    image: consul:0.8.0
    depends_on:
      - "seed"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_HTTP_ADDR=0.0.0.0"
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -retry-join=seed:8301
      - -ui    
      - -node-id=d3c15603-463a-2197-016d-a37959e10101